version: '3.8'

services:
  app:
    build: .
#    command: sh -c "sleep 10 && gunicorn --timeout 120 --workers=2 --worker-class=gevent --bind 0.0.0.0:8000 breadberry_web.wsgi:application"
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - .:/app
      - ./alembic.ini:/app/alembic.ini

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_NAME}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    env_file:
      - .env

  alembic:
    build: .
    depends_on:
      - db
    environment:
      - ${POSTGRES_URL}$
    command: >
      sh -c "sleep 5 &&
      alembic upgrade head &&
      tail -f /dev/null"
    volumes:
      - .:/app
      - ./alembic.ini:/app/alembic.ini
volumes:
  postgres_data: